
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Jul 18 2025 15:59:35 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aboutpage2026 extends ContentItem {
    public bannerimage!: Elements.AssetsElement;
    public aboutheading!: Elements.TextElement;
    public aboutcontent!: Elements.RichTextElement;
    public aboutvideolink!: Elements.TextElement;
    public aboutvideodescription!: Elements.TextElement;
    public testimonialsheading!: Elements.TextElement;
    public testimonialssubheading!: Elements.TextElement;
    public testimonialitems!: Elements.LinkedItemsElement<ContentItem>;
    public pillaritems!: Elements.LinkedItemsElement<ContentItem>;
    public visitorprofileheading!: Elements.TextElement;
    public visitorprofiledescription!: Elements.TextElement;
    public visitorprofileitems!: Elements.LinkedItemsElement<ContentItem>;
    public exhibitorprofileheading!: Elements.TextElement;
    public exhbitorprofiledescription!: Elements.TextElement;
    public exhibitorprofileitems!: Elements.LinkedItemsElement<ContentItem>;
    public whyvisitimage!: Elements.AssetsElement;
    public whyvisitcontent!: Elements.RichTextElement;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
