
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Jul 22 2025 16:15:36 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Conferenceitem extends ContentItem {
    public heading!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public galleryheading!: Elements.TextElement;
    public galleryimages!: Elements.AssetsElement;
}
