
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Jul 14 2025 15:27:55 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Globalcomponent extends ContentItem {
    public ipslogo!: Elements.AssetsElement;
    public landdepartmentlogo!: Elements.AssetsElement;
    public menuitems!: Elements.LinkedItemsElement<ContentItem>;
    public mobile!: Elements.TextElement;
    public email!: Elements.TextElement;
    public address!: Elements.TextElement;
    public facebooklink!: Elements.TextElement;
    public instagramlink!: Elements.TextElement;
    public linkedinlink!: Elements.TextElement;
    public xtwiterlink!: Elements.TextElement;
    public youtubelink!: Elements.TextElement;
    public organizedbytext!: Elements.TextElement;
    public organizedbylogo!: Elements.AssetsElement;
    public copyrighttext!: Elements.TextElement;
    public policyitems!: Elements.LinkedItemsElement<ContentItem>;
}
