
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Jul 18 2025 15:59:35 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepage2026 extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public bannerlogo!: Elements.AssetsElement;
    public bannerimage!: Elements.AssetsElement;
    public bannervideolink!: Elements.TextElement;
    public bannercta!: Elements.LinkedItemsElement<ContentItem>;
    public statsitems!: Elements.LinkedItemsElement<ContentItem>;
    public videoheading!: Elements.TextElement;
    public videodescription!: Elements.TextElement;
    public videolink!: Elements.TextElement;
    public pillarsheading!: Elements.TextElement;
    public pillarsitems!: Elements.LinkedItemsElement<ContentItem>;
    public featuresheading!: Elements.TextElement;
    public featureitems!: Elements.LinkedItemsElement<ContentItem>;
    public sideactivitesheading!: Elements.TextElement;
    public sideactivitiesitems!: Elements.LinkedItemsElement<ContentItem>;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
