
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Jul 14 2025 14:58:33 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Menuitem extends ContentItem {
    public name!: Elements.TextElement;
    public link!: Elements.TextElement;
    public target!: Elements.NumberElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
    public setasheading!: Elements.NumberElement;
}
