
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Jul 14 2025 14:16:30 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Partners extends ContentItem {
    public pageTitle!: Elements.TextElement;
    public heading!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
    public metaTitle!: Elements.TextElement;
    public metaDescription!: Elements.TextElement;
    public seometadataPagetitle!: Elements.TextElement;
    public seometadataMetatitle!: Elements.TextElement;
    public seometadataMetadescription!: Elements.TextElement;
    public seometadataMetakeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                if (elementName === 'seometadata__pagetitle') {
                    return 'seometadataPagetitle';
                }
                if (elementName === 'seometadata__metatitle') {
                    return 'seometadataMetatitle';
                }
                if (elementName === 'seometadata__metadescription') {
                    return 'seometadataMetadescription';
                }
                if (elementName === 'seometadata__metakeywords') {
                    return 'seometadataMetakeywords';
                }
                return elementName;
            })
        });
    }
}
